### ISSUE TITLE
Sane (De)Serialize impl for Password

### ISSUE THREAD

**Issue by stadust** [stadust/dash-rs#11]
Right now there isn't one, #9 adds a derive for them, which is the same we had in GDCF. This was done solely such that deriving Serialize for the there-added `Level` struct was possible.

The derived impl is pretty suboptimal though, since the standard serialization is way too noisy for what's essentially just an integer. A simpler default (de)serialization would be nie

**Comment by stadust** [comment]
Preferably one that matches the `Featured` impls

**Comment by zRyder** [comment]
Commenting so you can assign this to me (I finished already)
