### ISSUE TITLE
Dont go through str APIs in password decoding

### ISSUE THREAD

**Issue by stadust** [stadust/dash-rs#12]
https://github.com/stadust/dash-rs/blob/9f1e12a3520840a9ad0888a6d3e495a50bf3a3c4/src/model/level/mod.rs#L302-L304
Here we convert ASCII code points to a string, only to then parse that string into an int. We can just subtract `'0'` from the ASCII code points to reach the same goal (modulo some bounds checking)

**Comment by zRyder** [comment]
Commenting on this so I can actually be assigned the issue

**Comment by stadust** [comment]
Oh we already had an issue for this lol. Oh well, #21 is an addition to this then, ryder's gonna fix both of 'em :pog:
