### ISSUE TITLE
Eliminate .expect in Password decoding

### ISSUE THREAD

**Issue by stadust** [stadust/dash-rs#21]
This .expect can easily be triggered by malicious user data
https://github.com/stadust/dash-rs/blob/1b992f949b060a9c4227313655e829a829355e80/src/model/level/mod.rs#L350

Ryder is working on this one and once he comments on this issue or something I can assign it to him :pog:

**Comment by zRyder** [comment]
Hi I commented on this

**Comment by stadust** [comment]
Closed by #23
