### ISSUE TITLE
ICDX fails to parse

### ISSUE THREAD

**Issue by stadust** [stadust/dash-rs#36]
https://pointercrate.com/demonlist/259/

Might be related to #33

**Comment by kyurime** [comment]
Unfortunately, I don't think #33 applies here - it'll only apply to levels published after 1.9 using an external client. 
If I remember correctly, the GD servers compressed older levels a slight bit differently than how new levels are done, that might be your issue.
Would be helpful if where it failed parsing/what it failed parsing was posted as well.

**Comment by stadust** [comment]
Well pointercrate' extremely helpful error reporting tells me `[2020-12-20T19:04:53Z ERROR pointercrate::gd] Error storing demon 'ICE Carbon Diablo X': MalformedLevelData`. I'mma add a few more logging statements to dash-rs and pointercrate and report back haha

**Comment by stadust** [comment]
Good news! Its not the compression. Its missing some value in the metadata section: `[2020-12-20T19:09:54Z ERROR pointercrate::gd] Error processing level data: Deserialize("None at index None caused missing field `kA4`")`
